
import { Invoice } from "@/pages/Invoices";

export const mockInvoices: Invoice[] = [
  {
    id: "inv001",
    invoiceNumber: "INV-2025-001",
    date: "2025-04-15",
    amount: 1250.00,
    unitId: "A-101",
    propertyName: "Sunset Apartments",
    contractorName: "Elite Plumbing Co.",
    faultType: "Plumbing",
    status: "Approved",
    handler: "John Smith",
    propertyDetails: "123 Main Street, Building A",
    contractorDetails: "Elite Plumbing Co. - License #PL12345",
    estimatedAmount: 1200.00
  },
  {
    id: "inv002",
    invoiceNumber: "INV-2025-002",
    date: "2025-04-12",
    amount: 450.75,
    unitId: "B-205",
    propertyName: "Ocean View Condos",
    contractorName: "Sparky Electrical",
    faultType: "Electrical",
    status: "Pending Review",
    handler: "Jane Doe",
    propertyDetails: "456 Beach Road, Building B",
    contractorDetails: "Sparky Electrical - License #EL54321",
    estimatedAmount: 500.00
  },
  {
    id: "inv003",
    invoiceNumber: "INV-2025-003",
    date: "2025-04-10",
    amount: 3200.50,
    unitId: "C-310",
    propertyName: "Mountain Lodge",
    contractorName: "Structural Solutions Inc.",
    faultType: "Structural",
    status: "In Review",
    handler: "Alex Johnson",
    propertyDetails: "789 Mountain View Drive",
    contractorDetails: "Structural Solutions Inc. - License #ST98765",
    estimatedAmount: 3000.00
  },
  {
    id: "inv004",
    invoiceNumber: "INV-2025-004",
    date: "2025-04-08",
    amount: 875.25,
    unitId: "A-203",
    propertyName: "Sunset Apartments",
    contractorName: "Appliance Fix",
    faultType: "Appliance",
    status: "Not Approved",
    handler: "Sarah Williams",
    propertyDetails: "123 Main Street, Building A",
    contractorDetails: "Appliance Fix - License #AP24680",
    estimatedAmount: 750.00
  },
  {
    id: "inv005",
    invoiceNumber: "INV-2025-005",
    date: "2025-04-05",
    amount: 1875.00,
    unitId: "D-401",
    propertyName: "City Lofts",
    contractorName: "HVAC Experts",
    faultType: "HVAC",
    status: "Approved",
    handler: "John Smith",
    propertyDetails: "567 Downtown Avenue",
    contractorDetails: "HVAC Experts - License #HV13579",
    estimatedAmount: 2000.00
  },
  {
    id: "inv006",
    invoiceNumber: "INV-2025-006",
    date: "2025-04-02",
    amount: 625.50,
    unitId: "B-102",
    propertyName: "Ocean View Condos",
    contractorName: "LockMaster Security",
    faultType: "Security",
    status: "Pending Review",
    handler: "Jane Doe",
    propertyDetails: "456 Beach Road, Building B",
    contractorDetails: "LockMaster Security - License #LM11223",
    estimatedAmount: 600.00
  },
  {
    id: "inv007",
    invoiceNumber: "INV-2025-007",
    date: "2025-03-30",
    amount: 2150.75,
    unitId: "C-205",
    propertyName: "Mountain Lodge",
    contractorName: "Roofing Pros",
    faultType: "Roofing",
    status: "Approved",
    handler: "Alex Johnson",
    propertyDetails: "789 Mountain View Drive",
    contractorDetails: "Roofing Pros - License #RF44556",
    estimatedAmount: 2200.00
  }
];
